name: release

on:
  push:
    tags: ["v*"]
  workflow_dispatch:
env:
  ALPINE_VERSION: 3.23
jobs:
  build-binaries:
    strategy:
      fail-fast: false
      matrix:
        arch: ["i386","amd64","arm32v7","arm64"]
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        exclude:
          - arch: amd64
            runner: ubuntu-24.04-arm
          - arch: i386
            runner: ubuntu-24.04-arm
          - arch: arm64
            runner: ubuntu-24.04
          - arch: arm32v7
            runner: ubuntu-24.04
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6

      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist community/fio
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist community/libqrencode
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist community/redis
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/7zip
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/curl
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/htop
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/iperf3
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/iproute2
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/lsof
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/mariadb
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/nano
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/netcat-openbsd
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/nmap
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/pigz
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/postgresql17
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/procps-ng
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/rsync
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/socat
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/strace
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/tcpdump
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/vim
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist main/wget
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist custom/mysql57
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist custom/mysql80
      - run: docker build --build-arg BUILDARCH="$( echo ${{ matrix.arch }} | sed 's,arm64,arm64v8,')" --build-arg ALPINE_VERSION="${ALPINE_VERSION}" --platform="linux/$(echo ${{ matrix.arch }} | sed 's,arm32v7,arm/v7,')" -o=dist custom/mysql84

      - run: |
          for file in dist/*; do
            mv "$file" "${file}_${GITHUB_REF_NAME}_linux_${{ matrix.arch }}"
          done

      - uses: actions/upload-artifact@v4
        with:
          name: static-binaries-artifact-${{ matrix.arch }}
          path: dist/*
          retention-days: 1
          if-no-files-found: error

  merge-binaries:
    runs-on: ubuntu-24.04
    needs: build-binaries
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: static-binaries-artifact-*
          path: dist
          merge-multiple: true

      - run: cd dist && sha256sum * > SHA256SUMS

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          generate_release_notes: true
